services:
  backend:
    image: mmozzano/penguin-calendar-backend:latest
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=super-secret-key-change-this-for-production
    volumes:
      - penguin_data:/app/data
      
  frontend:
    image: mmozzano/penguin-calendar-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  penguin_data: